sudo: required
env:
  global:
  - DIST_REPO="f5-sphinx-theme"
services:
- docker
language: python
python:
- '2.7'
before_install:
- git config --global user.email "OpenStack_TravisCI@f5.com"
- git config --global user.name "Travis F5 Openstack"
install:
- gem install html-proofer
- pip install ./
script:
- htmlproofer --check_html --checks-to-ignore "LinkCheck,ImageCheck,ScriptCheck" --report_invalid_tags --report-script-embeds f5_sphinx_theme/
deploy:
- provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  server: https://pypi.python.org.pypi
  on:
    tags: true
  skip_cleanup: true
